# Generated by Django 3.2 on 2021-05-25 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='resultado',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
