# Generated by Django 3.2 on 2021-05-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar'),
        ),
    ]
