# Generated by Django 3.2 on 2021-05-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
    ]
